// Autogenerated by geninfo.sh, do not edit

package gcewing.lighting;

public class Info {
	static final String modName = "Greg's Lighting";
	static final String modID = "GregsLighting";
	static final String modPackage = "lighting";
	static final String versionNumber = "1.9.0";
	static final String versionBounds = "[1.9,1.10)";
}
